FROM python:3.13.5

RUN echo "Building RQ Worker Docker Image"


WORKDIR .

# Copy only necessary files — all code from backend dir
COPY . .

# Install dependencies
RUN pip install -r requirements.txt

# Set env variable so your imports work like `from app.services...`
ENV PYTHONPATH=/app

# Run the RQ worker (queue = default)
# CMD ["rq", "worker", "default"]
CMD ["rq", "worker", "default", "--url", "redis://redis:6379", "--timeout", "1200"]