"""
Project router for CRUD operations.

This module provides FastAPI endpoints for project management:
- Create, Read, Update, Delete (CRUD) operations
- List all projects
- Clear project data

All endpoints are protected and require authentication (can be added via dependencies).
"""

import logging
import asyncio
from typing import List, Optional, Dict, Tuple
from fastapi import (
    APIRouter,
    HTTPException,
    status,
    Path,
    Depends,
    UploadFile,
    File,
    Form,
    Query,
    BackgroundTasks,
)
from fastapi.responses import Response
from bson.errors import InvalidId
import uuid

# Import project service functions
from ....domain.projects import services
from .auth import get_current_user
from ....adapters.mongo.client import db
from ....domain.projects.schemas import (
    ProjectCreate,
    ProjectUpdate,
    ProjectOut,
    ProjectStatus,
)
from ....domain.projects.orchestration import ProjectOrchestrationService
from ....domain.projects.file_storage import FileStorageService
from ....domain.parsing.storage.document_store import DocumentStore
from ....domain.progress.events import ProgressEvent, Stage, Status
from .websocket import get_progress_publisher
import time

logger = logging.getLogger(__name__)


def require_admin(current_user: dict = Depends(get_current_user)) -> dict:
    """
    Dependency to require admin access.
    
    Args:
        current_user: Current authenticated user (from JWT token)
    
    Returns:
        User dictionary if admin, otherwise raises HTTPException
    
    Raises:
        HTTPException: If user is not an admin (403)
    """
    if not current_user.get("is_admin", False):
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin access required",
        )
    return current_user

# Create router with prefix and tags
# All routes will be under /api/v1/projects
projects_router = APIRouter(prefix="/api/v1/projects", tags=["projects"])

# Global orchestration service instance (will be injected in main.py)
_orchestration_service: Optional[ProjectOrchestrationService] = None

# Global file storage service instance (will be injected in main.py)
_file_storage_service: Optional[FileStorageService] = None

# Track background upload processing tasks
_upload_processing_tasks: Dict[str, asyncio.Task] = {}


def set_orchestration_service(service: ProjectOrchestrationService) -> None:
    """Set the global orchestration service instance."""
    global _orchestration_service
    _orchestration_service = service
    logger.info("Project orchestration service set for projects router")


def _get_orchestration_service() -> ProjectOrchestrationService:
    """Get the orchestration service instance."""
    if _orchestration_service is None:
        raise RuntimeError("Project orchestration service not initialized")
    return _orchestration_service


def set_file_storage_service(service: FileStorageService) -> None:
    """Set the global file storage service instance."""
    global _file_storage_service
    _file_storage_service = service
    logger.info("File storage service set for projects router")


def _get_file_storage_service() -> FileStorageService:
    """Get the file storage service instance."""
    if _file_storage_service is None:
        raise RuntimeError("File storage service not initialized")
    return _file_storage_service


@projects_router.post(
    "",
    response_model=ProjectOut,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new project",
    description="Create a new project with name, description, and optional tags.",
)
async def create_project(body: ProjectCreate):
    """
    Create a new project.

    This endpoint creates a new project in the database. The project ID
    is automatically generated by MongoDB.

    Required fields:
    - name: Project name (max 200 chars)
    - global_objective_type: Type of global objective
    - global_objective_target: Target magnitude of change

    Args:
        body: ProjectCreate schema with project data

    Returns:
        ProjectOut: Created project with ID and timestamps

    Raises:
        HTTPException: If validation fails (400) or creation fails (500)
    """
    try:
        # Create project (only name is required, objective fields can be set later)
        logger.info(f"Creating project: {body.name}")
        project = await services.create(body)
        return project
    except ValueError as e:
        # Validation errors from repository
        logger.warning(f"Validation error creating project: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions
        raise
    except Exception as e:
        logger.error(f"Error creating project: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create project: {str(e)}",
        )


@projects_router.get(
    "",
    response_model=List[ProjectOut],
    summary="List all projects",
    description="Get a list of all projects in the system.",
)
async def list_projects():
    """
    List all projects.

    Returns all projects from the database. For large datasets,
    consider adding pagination in the future.

    Returns:
        List[ProjectOut]: List of all projects

    Raises:
        HTTPException: If listing fails (500)
    """
    try:
        logger.info("Listing all projects")
        projects = await services.list_all()
        return projects
    except Exception as e:
        logger.error(f"Error listing projects: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to list projects: {str(e)}",
        )


@projects_router.delete(
    "/delete-all-user-data",
    status_code=status.HTTP_200_OK,
    summary="Delete all user data",
    description="Delete all projects, scenarios, and files associated with the current user.",
)
async def delete_all_user_data(
    current_user: dict = Depends(get_current_user),
):
    """
    Delete all data associated with the current user.

    This endpoint permanently deletes:
    - All projects created by the user
    - All scenarios for those projects
    - All files uploaded for those projects

    **Warning**: This action cannot be undone!

    Args:
        current_user: Current authenticated user (from JWT token)

    Returns:
        Dictionary with deletion counts

    Raises:
        HTTPException: If deletion fails (500)
    """
    try:
        user_id = str(current_user["_id"])
        result = await services.delete_all_user_data(user_id)
        return result
    except Exception as e:
        logger.error(f"Error deleting all user data: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete all user data: {str(e)}",
        )


@projects_router.get(
    "/{project_id}",
    response_model=ProjectOut,
    summary="Get a project by ID",
    description="Retrieve a specific project by its ID.",
)
async def get_project(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Get a project by ID.

    Args:
        project_id: MongoDB ObjectId as string

    Returns:
        ProjectOut: Project data

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Getting project: {project_id}")
        project = await services.get(project_id)

        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        return project
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error getting project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get project: {str(e)}",
        )


@projects_router.patch(
    "/{project_id}",
    response_model=ProjectOut,
    summary="Update a project",
    description="Partially update a project. Only provided fields will be updated.",
)
async def update_project(
    patch: ProjectUpdate,
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Update a project.

    This endpoint supports partial updates (PATCH semantics). Only fields
    provided in the request body will be updated. The updated_at timestamp
    is automatically updated.

    Args:
        patch: ProjectUpdate schema with fields to update
        project_id: MongoDB ObjectId as string

    Returns:
        ProjectOut: Updated project data

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Updating project: {project_id}")
        project = await services.update(project_id, patch)

        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        return project
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error updating project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update project: {str(e)}",
        )


@projects_router.delete(
    "/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a project",
    description="Delete a project from the system. This only deletes the project document, not associated data.",
)
async def delete_project(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Delete a project.

    This endpoint deletes the project document from the database.
    Note: This does NOT delete associated data (entities, relations, etc.).
    Use the clear_project_data endpoint if you need to clean up related data.

    Args:
        project_id: MongoDB ObjectId as string

    Returns:
        HTTP 204 No Content on success

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Deleting project: {project_id}")
        await services.clear_data(project_id)
        deleted = await services.delete(project_id)

        if not deleted:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Return 204 No Content (no response body)
        return None
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error deleting project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete project: {str(e)}",
        )


@projects_router.post(
    "/{project_id}/clear-data",
    summary="Clear project data",
    description="Delete all data associated with a project (entities, relations, etc.) but keep the project itself.",
)
async def clear_project_data(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Clear all data associated with a project.

    This endpoint deletes all related data (entities, relations, etc.)
    for a project, but keeps the project document itself. This is useful
    for resetting a project without deleting it.

    WARNING: This is a destructive operation. Use with caution.

    Args:
        project_id: MongoDB ObjectId as string

    Returns:
        Dictionary with deletion counts for each collection

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Clearing data for project: {project_id}")
        result = await services.clear_data(project_id)

        if "error" in result:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result["error"],
            )

        return result
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error clearing project data {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to clear project data: {str(e)}",
        )


@projects_router.patch(
    "/{project_id}/status",
    response_model=ProjectOut,
    summary="Update project status",
    description="Update the status of a project (draft, processing, validation, completed).",
)
async def update_project_status(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    status_value: ProjectStatus = Query(..., description="New project status"),
):
    """
    Update project status.

    Args:
        project_id: MongoDB ObjectId as string
        status_value: New project status (draft, processing, validation, completed)

    Returns:
        ProjectOut: Updated project data

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Updating project status: {project_id} -> {status_value}")

        # Create update patch with status
        patch = ProjectUpdate(status=status_value)
        project = await services.update(project_id, patch)

        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        return project
    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating project status {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update project status: {str(e)}",
        )


async def _process_uploaded_files_background(
    job_id: str,
    file_data: List[
        Tuple[bytes, str, str, str]
    ],  # (file_bytes, filename, doc_id, artifact_type)
    project_id: str,
    user_id: str,
    store_in_pinecone: bool,
    process_base_case: bool = False,
):
    """Process uploaded files in background with progress updates.

    Args:
        job_id: Unique job identifier for progress tracking
        file_data: List of tuples (file_bytes, filename, doc_id, artifact_type)
        project_id: Project identifier
        user_id: User identifier
        store_in_pinecone: Whether to store entities in Pinecone
    """
    logger.info(
        f"[Background Task] Starting processing for job {job_id} with {len(file_data)} files"
    )
    
    # Wait briefly to allow WebSocket connection to be established
    # This ensures the frontend receives real-time progress updates
    await asyncio.sleep(0.5)
    logger.info(f"[Background Task] Delay complete, starting actual processing for job {job_id}")
    
    try:
        publisher = get_progress_publisher()
        orchestration = _get_orchestration_service()

        logger.info(
            f"[Background Task] Retrieved publisher and orchestration service for job {job_id}"
        )

        total_files = len(file_data)
        successful = 0
        errors = []

        # Emit start event
        logger.info(f"[Background Task] Publishing start event for job {job_id}")
        publisher.publish(
            job_id,
            ProgressEvent(
                job_id=job_id,
                stage=Stage.PROCESSING,
                status=Status.STARTED,
                progress=0,
                seq=0,
                meta={
                    "project_id": project_id,
                    "total_files": total_files,
                    "current_stage": "Processing uploaded files",
                },
            ),
        )
        logger.info(f"[Background Task] Start event published for job {job_id}")

        # Process each file sequentially
        for idx, (file_bytes, filename, doc_id, artifact_type) in enumerate(
            file_data, 1
        ):
            logger.info(
                f"[Background Task] Processing file {idx}/{total_files}: {filename} (doc_id: {doc_id}, type: {artifact_type})"
            )
            try:
                # Emit file start event
                publisher.publish(
                    job_id,
                    ProgressEvent(
                        job_id=job_id,
                        stage=Stage.PROCESSING,
                        status=Status.IN_PROGRESS,
                        progress=int((idx - 1) / total_files * 100),
                        seq=idx * 2 - 1,
                        meta={
                            "project_id": project_id,
                            "current_file": filename,
                            "file_index": idx,
                            "total_files": total_files,
                            "artifact_type": artifact_type,
                            "current_stage": f"Processing {artifact_type} file {idx} of {total_files}: {filename}",
                        },
                    ),
                )

                if artifact_type == "base_case" and process_base_case:
                    # Process the file
                    logger.info(
                        f"[Background Task] Calling orchestration.process_base_case_file for {filename}"
                    )
                    result = await orchestration.process_base_case_file(
                        file_bytes=file_bytes,
                        filename=filename,
                        file_id=doc_id,
                        project_id=project_id,
                        user_id=user_id,
                        store_in_pinecone=store_in_pinecone,
                    )
                    logger.info(
                        f"[Background Task] Processing complete for {filename}: {result.get('status', 'unknown')}"
                    )
                elif artifact_type == "tabular_data":
                    # Process the file
                    logger.info(
                        f"[Background Task] Calling orchestration.process_tabular_data_file for {filename}"
                    )
                    result = await orchestration.process_tabular_data_file(
                        file_bytes=file_bytes,
                        filename=filename,
                        file_id=doc_id,
                        project_id=project_id,
                        user_id=user_id,
                        store_in_pinecone=store_in_pinecone,
                        job_id=job_id,
                        progress_publisher=publisher,
                    )
                    logger.info(
                        f"[Background Task] Processing complete for {filename}: {result.get('status', 'unknown')}"
                    )
                else:
                    logger.warning(
                        f"[Background Task] Unknown artifact_type '{artifact_type}' for file {filename}, skipping processing"
                    )
                    result = {
                        "status": "skipped",
                        "reason": f"Unknown artifact_type: {artifact_type}",
                    }

                successful += 1

                # Emit file complete event
                publisher.publish(
                    job_id,
                    ProgressEvent(
                        job_id=job_id,
                        stage=Stage.PROCESSING,
                        status=Status.IN_PROGRESS,
                        progress=int(idx / total_files * 100),
                        seq=idx * 2,
                        meta={
                            "project_id": project_id,
                            "current_file": filename,
                            "file_index": idx,
                            "total_files": total_files,
                            "artifact_type": artifact_type,
                            "current_stage": f"Completed {artifact_type} file {idx} of {total_files}",
                            "tables_extracted": result.get("tables_extracted", 0),
                            "entities_extracted": result.get("entities_extracted", 0),
                        },
                    ),
                )

            except Exception as e:
                logger.error(f"Error processing file {filename}: {e}", exc_info=True)
                errors.append(
                    {
                        "filename": filename,
                        "doc_id": doc_id,
                        "error": str(e),
                    }
                )

        # Emit completion event
        final_status = (
            Status.COMPLETED
            if successful == total_files
            else (Status.COMPLETED if successful > 0 else Status.FAILED)
        )

        logger.info(
            f"[Background Task] Processing complete for job {job_id}: {successful}/{total_files} files successful"
        )
        publisher.publish(
            job_id,
            ProgressEvent(
                job_id=job_id,
                stage=(
                    Stage.COMPLETE if final_status == Status.COMPLETED else Stage.ERROR
                ),
                status=final_status,
                progress=100,
                seq=len(file_data) * 2 + 1,
                meta={
                    "project_id": project_id,
                    "total_files": total_files,
                    "successful_files": successful,
                    "failed_files": len(errors),
                    "errors": errors if errors else None,
                    "current_stage": f"Processing complete: {successful}/{total_files} files processed successfully",
                },
            ),
        )

    except Exception as e:
        logger.error(
            f"Background processing failed for job {job_id}: {e}", exc_info=True
        )
        publisher.publish(
            job_id,
            ProgressEvent(
                job_id=job_id,
                stage=Stage.ERROR,
                status=Status.FAILED,
                progress=0,
                seq=999,
                meta={"error": str(e)},
            ),
        )
    finally:
        # Cleanup
        logger.info(f"[Background Task] Cleaning up task for job {job_id}")
        if job_id in _upload_processing_tasks:
            del _upload_processing_tasks[job_id]
            logger.info(
                f"[Background Task] Task removed from tracking for job {job_id}"
            )


@projects_router.post(
    "/{project_id}/upload-files",
    summary="Upload files for a project",
    description="Upload base case documents and tabular data files for a project. Total file size limit is 25MB. Tabular data files will be automatically processed to extract tables and entities.",
)
async def upload_project_files(
    background_tasks: BackgroundTasks,
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    base_case_files: Optional[List[UploadFile]] = File(
        None, description="Base case report documents (PDF)"
    ),
    tabular_data_files: Optional[List[UploadFile]] = File(
        None, description="Tabular data files (PDF, Excel, CSV)"
    ),
    store_in_pinecone: bool = Query(
        True,
        description="Whether to store extracted entities in Pinecone (default: True)",
    ),
    current_user: dict = Depends(get_current_user),
):
    """
    Upload files for a project.

    This endpoint accepts multiple files for base case documents and tabular data.
    Files are validated for type and total size (25MB limit across all files).

    For tabular data files, the system will automatically:
    - Extract tables from PDF files
    - Extract entities using LLM with MSIO ontology
    - Store tables and entities/edges in MongoDB
    - Store entities in Pinecone by default (can be disabled by setting store_in_pinecone=False)

    Args:
        project_id: MongoDB ObjectId as string
        base_case_files: List of base case PDF files
        tabular_data_files: List of tabular data files (PDF, Excel, CSV)
        store_in_pinecone: Whether to store extracted entities in Pinecone (default: True)
        current_user: Current authenticated user (from JWT token)

    Returns:
        Dictionary with uploaded document IDs, processing status, and processing results

    Raises:
        HTTPException: If validation fails (400) or project not found (404)
    """
    try:
        # Get user_id from authenticated user
        user_id = str(current_user["_id"])

        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Validate file types and sizes
        MAX_TOTAL_SIZE = 25 * 1024 * 1024  # 25MB in bytes
        ALLOWED_BASE_CASE_TYPES = ["application/pdf"]
        ALLOWED_TABULAR_TYPES = [
            "application/pdf",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",  # Excel
            "application/vnd.ms-excel",  # Excel (old)
            "text/csv",
        ]

        total_size = 0
        document_ids = []

        # Store file bytes for processing (only PDFs can be processed currently)
        # Combined list: (file_bytes, filename, doc_id, artifact_type)
        files_to_process = []

        # Process base case files
        base_case_doc_ids = []
        if base_case_files:
            file_storage = _get_file_storage_service()
            for file in base_case_files:
                if file.content_type not in ALLOWED_BASE_CASE_TYPES:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid file type for base case: {file.content_type}. Only PDF is allowed.",
                    )

                file_bytes = await file.read()
                total_size += len(file_bytes)

                if total_size > MAX_TOTAL_SIZE:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Total file size exceeds 25MB limit",
                    )

                # Store file in GridFS
                doc_id = file_storage.store_file(
                    file_bytes=file_bytes,
                    filename=file.filename or "unknown.pdf",
                    project_id=project_id,
                    artifact_type="base_case",
                    content_type=file.content_type,
                )
                base_case_doc_ids.append(doc_id)
                document_ids.append(doc_id)
                logger.info(
                    f"Uploaded and stored base case file: {file.filename} -> {doc_id}"
                )

                # Store file data for processing (only PDFs can be processed currently)
                if file.content_type == "application/pdf":
                    files_to_process.append(
                        (
                            file_bytes,
                            file.filename or "unknown.pdf",
                            doc_id,
                            "base_case",
                        )
                    )
                    logger.info(
                        f"Added {file.filename} to processing queue (base_case)"
                    )
                else:
                    logger.info(f"Skipping {file.filename} - not a PDF, cannot process")

        # Process tabular data files
        tabular_doc_ids = []
        if tabular_data_files:
            file_storage = _get_file_storage_service()

            for idx, file in enumerate(tabular_data_files, 1):
                if file.content_type not in ALLOWED_TABULAR_TYPES:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid file type for tabular data: {file.content_type}. Allowed: PDF, Excel, CSV.",
                    )

                file_bytes = await file.read()
                total_size += len(file_bytes)

                if total_size > MAX_TOTAL_SIZE:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Total file size exceeds 25MB limit",
                    )

                # Store file in GridFS
                doc_id = file_storage.store_file(
                    file_bytes=file_bytes,
                    filename=file.filename or "unknown",
                    project_id=project_id,
                    artifact_type="tabular_data",
                    content_type=file.content_type,
                )
                tabular_doc_ids.append(doc_id)
                document_ids.append(doc_id)
                logger.info(
                    f"Uploaded and stored tabular data file: {file.filename} -> {doc_id}"
                )

                # Store file data for processing (only PDFs can be processed currently)
                if file.content_type == "application/pdf":
                    files_to_process.append(
                        (file_bytes, file.filename or "unknown", doc_id, "tabular_data")
                    )
                    logger.info(
                        f"Added {file.filename} to processing queue (tabular_data)"
                    )
                else:
                    logger.info(f"Skipping {file.filename} - not a PDF, cannot process")

        # Validate at least one file was uploaded
        if not document_ids:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one file must be uploaded",
            )

        # Update project with document IDs, merging with existing documents
        update_data = {}
        if base_case_doc_ids:
            # Merge new base case documents with existing ones
            existing_base_case = project.base_case_documents or []
            update_data["base_case_documents"] = list(
                set(existing_base_case + base_case_doc_ids)
            )
        if tabular_doc_ids:
            # Merge new tabular data documents with existing ones
            existing_tabular = project.tabular_data_documents or []
            update_data["tabular_data_documents"] = list(
                set(existing_tabular + tabular_doc_ids)
            )

        # Update project with merged document lists
        update_patch = ProjectUpdate(**update_data)
        updated_project = await services.update(project_id, update_patch)
        logger.info(
            f"Updated project {project_id} with {len(base_case_doc_ids)} base case and {len(tabular_doc_ids)} tabular documents"
        )

        # Process files in background if any PDFs were uploaded
        if files_to_process:
            # Generate unique job ID for background processing
            job_id = str(uuid.uuid4())
            logger.info(
                f"Creating background task for job {job_id} with {len(files_to_process)} files "
                f"({sum(1 for _, _, _, at in files_to_process if at == 'base_case')} base_case, "
                f"{sum(1 for _, _, _, at in files_to_process if at == 'tabular_data')} tabular_data)"
            )

            # Publish start event
            publisher = get_progress_publisher()
            publisher.publish(
                job_id,
                ProgressEvent(
                    job_id=job_id,
                    stage=Stage.PROCESSING,
                    status=Status.STARTED,
                    progress=0,
                    seq=0,
                    meta={
                        "project_id": project_id,
                        "total_files": len(files_to_process),
                        "current_stage": "Processing uploaded files",
                    },
                ),
            )
            logger.info(f"Start event published for job {job_id}")

            # Schedule background task for file processing using FastAPI's BackgroundTasks
            # This ensures the task runs AFTER the response is sent to the client
            background_tasks.add_task(
                _process_uploaded_files_background,
                job_id=job_id,
                file_data=files_to_process,
                project_id=project_id,
                user_id=user_id,
                store_in_pinecone=store_in_pinecone,
            )

            logger.info(
                f"Background task scheduled for {len(files_to_process)} files (job_id: {job_id})"
            )
            logger.info(f"Background task will run after response is sent")

            # Return with job info
            return {
                "job_id": job_id,
                "project_id": project_id,
                "status": "queued",
                "message": "Files uploaded successfully. Processing started in background.",
                "websocket_url": f"/api/v1/ws/progress/{job_id}",
                "base_case_documents": base_case_doc_ids,
                "tabular_data_documents": tabular_doc_ids,
                "total_files": len(document_ids),
                "total_size_bytes": total_size,
            }
        else:
            # No processing needed (no PDFs to process)
            logger.info(f"No PDF files to process. Returning success response.")
            return {
                "project_id": project_id,
                "base_case_documents": base_case_doc_ids,
                "tabular_data_documents": tabular_doc_ids,
                "total_files": len(document_ids),
                "total_size_bytes": total_size,
                "message": "Files uploaded successfully. No processing required.",
            }

    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except RuntimeError as e:
        logger.error(f"Orchestration service not initialized: {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Document processing service not available",
        )
    except Exception as e:
        logger.error(
            f"Error uploading files for project {project_id}: {e}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to upload files: {str(e)}",
        )


@projects_router.post(
    "/{project_id}/run-analysis",
    summary="Run or re-run analysis for a project",
    description="Trigger document processing and analysis for a project. Requires objective details and documents to be uploaded.",
)
async def run_analysis(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Run or re-run analysis for a project.

    This endpoint triggers the document processing and analysis pipeline.
    It requires that the project has:
    - Global objective details set
    - At least one base case document uploaded
    - At least one tabular data document uploaded

    Args:
        project_id: MongoDB ObjectId as string

    Returns:
        Dictionary with analysis status and job information

    Raises:
        HTTPException: If project not found (404), missing requirements (400), or processing fails (500)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Validate requirements
        if not project.base_case_documents or len(project.base_case_documents) == 0:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one base case document is required. Please upload documents first.",
            )

        if (
            not project.tabular_data_documents
            or len(project.tabular_data_documents) == 0
        ):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one tabular data document is required. Please upload documents first.",
            )

        # Update project status to processing
        status_patch = ProjectUpdate(status=ProjectStatus.PROCESSING)
        await services.update(project_id, status_patch)

        # Note: This endpoint is deprecated. Use scenario run-analysis endpoint instead.
        # This endpoint no longer uses objectives (moved to scenarios).
        # Trigger document processing via orchestration service
        orchestration = _get_orchestration_service()
        # For backward compatibility, use empty objectives
        processing_result = await orchestration.process_project_documents(
            project_id=project_id,
            global_objective_type="",  # No longer used
            global_objective_target="",  # No longer used
            base_case_document_ids=project.base_case_documents,
            tabular_data_document_ids=project.tabular_data_documents,
        )

        logger.info(f"Analysis started for project {project_id}")

        return {
            "project_id": project_id,
            "status": "processing",
            "message": "Analysis started successfully",
            "processing_result": processing_result,
        }

    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except RuntimeError as e:
        logger.error(f"Orchestration service not initialized: {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Analysis service not available",
        )
    except Exception as e:
        logger.error(
            f"Error running analysis for project {project_id}: {e}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to run analysis: {str(e)}",
        )


@projects_router.delete(
    "/{project_id}/files/{file_id}",
    summary="Delete a project file",
    description="Delete a file from GridFS storage. This will also remove related scenarios and ingested data.",
    status_code=status.HTTP_200_OK,
)
async def delete_project_file(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    file_id: str = Path(..., description="File ID (GridFS ObjectId as string)"),
):
    """
    Delete a file from GridFS.

    This endpoint deletes a file stored in GridFS. Deleting a file will also
    affect related scenarios and any ingested/extracted data from that file.

    Args:
        project_id: MongoDB ObjectId as string
        file_id: GridFS ObjectId as string

    Returns:
        Success message with deletion confirmation

    Raises:
        HTTPException: If project not found (404), file not found (404), or invalid ID format (400)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Get file storage service
        file_storage = _get_file_storage_service()

        # Get file metadata to verify it exists and belongs to project
        metadata = file_storage.get_file_metadata(file_id)
        if not metadata:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"File not found: {file_id}",
            )

        # Verify file belongs to the project
        if metadata.get("project_id") != project_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"File does not belong to project {project_id}",
            )

        # Delete the file from GridFS
        deleted = file_storage.delete_file(file_id)
        if not deleted:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Failed to delete file: {file_id}",
            )

        # Delete all associated entities, relations, chunks, tables, and document metadata
        # Note: file_id is used as doc_id when processing files
        document_store = DocumentStore()
        entities_deleted = document_store.delete_entities_by_doc_id(file_id)
        relations_deleted = document_store.delete_relations_by_doc_id(file_id)
        chunks_deleted = document_store.delete_chunks_by_doc_id(file_id)
        tables_deleted = document_store.delete_tables_by_doc_id(file_id)
        document_deleted = document_store.delete_document(file_id)

        logger.info(
            f"Deleted file {file_id} and associated data: "
            f"{entities_deleted} entities, {relations_deleted} relations, "
            f"{chunks_deleted} chunks, {tables_deleted} tables"
        )

        # Remove file ID from project's document lists if present
        update_data = {}
        if project.base_case_documents and file_id in project.base_case_documents:
            update_data["base_case_documents"] = [
                doc_id for doc_id in project.base_case_documents if doc_id != file_id
            ]
        if project.tabular_data_documents and file_id in project.tabular_data_documents:
            update_data["tabular_data_documents"] = [
                doc_id for doc_id in project.tabular_data_documents if doc_id != file_id
            ]

        if update_data:
            await services.update(project_id, ProjectUpdate(**update_data))

        logger.info(f"Deleted file {file_id} from project {project_id}")

        return {
            "message": "File deleted successfully",
            "file_id": file_id,
            "project_id": project_id,
            "deleted_counts": {
                "entities": entities_deleted,
                "relations": relations_deleted,
                "chunks": chunks_deleted,
                "tables": tables_deleted,
            },
        }

    except ValueError as e:
        logger.warning(f"Invalid project_id or file_id format: {project_id}, {file_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            f"Error deleting file {file_id} for project {project_id}: {e}",
            exc_info=True,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete file: {str(e)}",
        )


@projects_router.get(
    "/{project_id}/files/{file_id}",
    summary="Download a project file",
    description="Retrieve a file by its ID from GridFS storage.",
)
async def download_project_file(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    file_id: str = Path(..., description="File ID (GridFS ObjectId as string)"),
):
    """
    Download a file from GridFS.

    This endpoint retrieves a file stored in GridFS and returns it with
    appropriate content-type headers for download.

    Args:
        project_id: MongoDB ObjectId as string
        file_id: GridFS ObjectId as string

    Returns:
        File content with appropriate headers

    Raises:
        HTTPException: If project not found (404), file not found (404), or invalid ID format (400)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Get file from storage
        file_storage = _get_file_storage_service()
        file_bytes = file_storage.get_file(file_id)

        if not file_bytes:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"File not found: {file_id}",
            )

        # Get file metadata for content-type and filename
        metadata = file_storage.get_file_metadata(file_id)
        if not metadata:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"File metadata not found: {file_id}",
            )

        # Verify file belongs to the project
        if metadata.get("project_id") != project_id:
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail=f"File does not belong to project {project_id}",
            )

        content_type = metadata.get("content_type", "application/octet-stream")
        filename = metadata.get("filename", "file")

        return Response(
            content=file_bytes,
            media_type=content_type,
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
            },
        )

    except ValueError as e:
        logger.warning(f"Invalid project_id or file_id format: {project_id}, {file_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            f"Error downloading file {file_id} for project {project_id}: {e}",
            exc_info=True,
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to download file: {str(e)}",
        )


@projects_router.get(
    "/{project_id}/files",
    summary="List project files",
    description="Get list of all files uploaded for a project.",
)
async def list_project_files(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    artifact_type: Optional[str] = Query(
        None, description="Filter by artifact type (base_case or tabular_data)"
    ),
):
    """
    List all files for a project.

    This endpoint retrieves metadata for all files stored in GridFS for the project.

    Args:
        project_id: MongoDB ObjectId as string
        artifact_type: Optional filter by artifact type

    Returns:
        Dictionary with lists of base case and tabular data files

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Get file storage service
        file_storage = _get_file_storage_service()

        # List files
        if artifact_type:
            files = file_storage.list_project_files(project_id, artifact_type)
            return {
                "project_id": project_id,
                "files": files,
                "artifact_type": artifact_type,
            }
        else:
            base_case_files = file_storage.list_project_files(project_id, "base_case")
            tabular_data_files = file_storage.list_project_files(
                project_id, "tabular_data"
            )
            return {
                "project_id": project_id,
                "base_case_files": base_case_files,
                "tabular_data_files": tabular_data_files,
                "total_files": len(base_case_files) + len(tabular_data_files),
            }

    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            f"Error listing files for project {project_id}: {e}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to list files: {str(e)}",
        )


@projects_router.get(
    "/{project_id}/entities",
    summary="Get entities for a project",
    description="Retrieve entities from the entities collection filtered by project_id and artifact_type",
)
async def get_project_entities(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    artifact_type: str = Query("base_case", description="Artifact type filter (default: base_case)"),
    current_user: dict = Depends(get_current_user),
):
    """
    Get entities for a project.
    
    Returns entities from the entities collection that match the project_id
    and artifact_type. For base_case entities, excludes entities with scenario_id
    to show only project-level base case entities.
    
    Args:
        project_id: Project identifier
        artifact_type: Artifact type filter (default: "base_case")
        current_user: Authenticated user
    
    Returns:
        Dictionary with project_id, artifact_type, entities list, and count
    """
    try:
        # Validate project_id format
        try:
            from bson import ObjectId
            ObjectId(project_id)
        except Exception:
            raise ValueError(f"Invalid project_id format: {project_id}")
        
        # Verify project exists and user has access
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        # Query entities collection
        entities_collection = db().entities
        query = {
            "properties.project_id": project_id,
            "properties.artifact_type": artifact_type,
        }
        
        # For base_case entities, exclude entities with scenario_id to show only project-level entities
        if artifact_type == "base_case":
            query["properties.scenario_id"] = {"$exists": False}
        
        entities = list(entities_collection.find(query, {"_id": 0}))
        
        # Convert ObjectId to string if present in nested structures
        for entity in entities:
            if "_id" in entity:
                entity["id"] = str(entity["_id"])
                del entity["_id"]
            elif "id" not in entity and "_id" in entity:
                entity["id"] = str(entity["_id"])
        
        logger.info(
            f"Retrieved {len(entities)} entities for project {project_id} "
            f"with artifact_type {artifact_type}"
        )
        
        return {
            "project_id": project_id,
            "artifact_type": artifact_type,
            "entities": entities,
            "count": len(entities),
        }
            
    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error fetching entities for project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to fetch entities: {str(e)}",
        )


@projects_router.get(
    "/{project_id}/report",
    summary="Get project report",
    description="Generate and retrieve markdown report for a project.",
)
async def get_project_report(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Get project report in markdown format.

    This endpoint generates a comprehensive markdown report including
    project details, extracted entities, cost estimates, and recommendations.

    Args:
        project_id: MongoDB ObjectId as string

    Returns:
        Dictionary with markdown report content

    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )

        # Generate report using orchestration service
        orchestration = _get_orchestration_service()
        markdown_content = await orchestration.generate_report(project_id)

        return {
            "project_id": project_id,
            "report": markdown_content,
            "format": "markdown",
        }

    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except RuntimeError as e:
        logger.error(f"Orchestration service not initialized: {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Report generation service not available",
        )
    except Exception as e:
        logger.error(
            f"Error generating report for project {project_id}: {e}", exc_info=True
        )
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate report: {str(e)}",
        )


@projects_router.delete(
    "/admin/clear-pinecone-index",
    status_code=status.HTTP_200_OK,
    summary="Clear all Pinecone index data (Admin only)",
    description="Delete all vectors from all namespaces in the Pinecone index. This is a destructive operation that cannot be undone.",
)
async def clear_pinecone_index(
    current_user: dict = Depends(require_admin),
    verify: bool = Query(
        False,
        description="Whether to verify deletion by checking index stats after deletion",
    ),
):
    """
    Clear all Pinecone index data.
    
    This endpoint permanently deletes all vectors from all namespaces in the Pinecone index.
    This operation:
    1. Enumerates all namespaces in the index
    2. Deletes all vectors from each namespace
    3. Optionally verifies the deletion
    
    **Warning**: This is a destructive operation that cannot be undone!
    This will delete ALL vector data for ALL projects in the system.
    
    Args:
        current_user: Current authenticated admin user (from JWT token)
        verify: Whether to verify deletion by checking index stats (default: False)
    
    Returns:
        Dictionary with deletion summary including:
        - namespaces_cleared: List of namespace names that were cleared
        - total_namespaces: Total number of namespaces found
        - verification_stats: Index stats after deletion (if verify=True)
    
    Raises:
        HTTPException: If user is not admin (403) or operation fails (500)
    """
    try:
        from ....domain.parsing.storage.vector_store import _get_pinecone_index
        
        index = _get_pinecone_index()
        
        # Step 1: Enumerate namespaces
        logger.info("Enumerating Pinecone namespaces for deletion")
        stats = index.describe_index_stats()
        namespaces = list(stats.get("namespaces", {}).keys())
        
        # If no explicit namespaces exist, Pinecone implicitly uses "__default__"
        if not namespaces:
            namespaces = ["__default__"]
            logger.info("No explicit namespaces found, using default namespace")
        
        logger.info(f"Found {len(namespaces)} namespace(s) to clear: {namespaces}")
        
        # Step 2: Delete everything per namespace
        namespaces_cleared = []
        for ns in namespaces:
            try:
                logger.info(f"Deleting all vectors from namespace: {ns}")
                index.delete(delete_all=True, namespace=ns)
                namespaces_cleared.append(ns)
                logger.info(f"Successfully deleted all vectors from namespace: {ns}")
            except Exception as e:
                logger.error(
                    f"Failed to delete vectors from namespace {ns}: {e}",
                    exc_info=True,
                )
                # Continue with other namespaces even if one fails
                continue
        
        # Step 3: Optional verification
        verification_stats = None
        if verify:
            logger.info("Verifying deletion (waiting 1 seconds for propagation)")
            time.sleep(1)  # Allow propagation
            try:
                stats_after = index.describe_index_stats()
                verification_stats = {
                    "total_vector_count": stats_after.get("total_vector_count", 0),
                    "namespaces": list(stats_after.get("namespaces", {}).keys()),
                }
                logger.info(f"Verification stats: {verification_stats}")
            except Exception as e:
                logger.warning(f"Failed to get verification stats: {e}")
        
        logger.info(
            f"Pinecone index cleared by admin user {current_user.get('email', 'unknown')}: "
            f"{len(namespaces_cleared)}/{len(namespaces)} namespaces cleared"
        )
        
        return {
            "message": "Pinecone index cleared successfully",
            "namespaces_cleared": namespaces_cleared,
            "total_namespaces": len(namespaces),
            "cleared_by": current_user.get("email", "unknown"),
            "verification_stats": verification_stats if verify else None,
        }
        
    except ValueError as e:
        logger.error(f"Pinecone configuration error: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Pinecone configuration error: {str(e)}",
        )
    except Exception as e:
        logger.error(f"Error clearing Pinecone index: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to clear Pinecone index: {str(e)}",
        )


# WebSocket Support (Future Enhancement)
# ======================================
#
# If real-time updates are needed for projects, WebSocket support can be added here.
# Example:
#
# @projects_router.websocket("/{project_id}/ws")
# async def project_websocket(websocket: WebSocket, project_id: str):
#     """
#     WebSocket endpoint for real-time project updates.
#
#     Clients can connect to receive real-time notifications when:
#     - Project data is updated
#     - Project data is added/deleted
#     """
#     await websocket.accept()
#     try:
#         # Subscribe to project change events
#         # Send updates as they occur
#         while True:
#             # Wait for events and send to client
#             await websocket.send_json({"type": "update", "data": {...}})
#     except WebSocketDisconnect:
#         # Client disconnected
#         pass
#
# This would require:
# 1. A pub/sub system (like the progress publisher used in files.py)
# 2. Event emission in repository methods
# 3. WebSocket connection management
#
# For now, standard REST endpoints are sufficient for CRUD operations.
