"""
Project router for CRUD operations.

This module provides FastAPI endpoints for project management:
- Create, Read, Update, Delete (CRUD) operations
- List all projects
- Clear project data

All endpoints are protected and require authentication (can be added via dependencies).
"""

import logging
from typing import List, Optional
from fastapi import APIRouter, HTTPException, status, Path, Depends, UploadFile, File, Form, Query
from bson.errors import InvalidId
import uuid

# Import project service functions
from ....domain.projects import services
from ....domain.projects.schemas import (
    ProjectCreate,
    ProjectUpdate,
    ProjectOut,
    ProjectStatus,
)
from ....domain.projects.orchestration import ProjectOrchestrationService

logger = logging.getLogger(__name__)

# Create router with prefix and tags
# All routes will be under /api/v1/projects
projects_router = APIRouter(prefix="/api/v1/projects", tags=["projects"])

# Global orchestration service instance (will be injected in main.py)
_orchestration_service: Optional[ProjectOrchestrationService] = None


def set_orchestration_service(service: ProjectOrchestrationService) -> None:
    """Set the global orchestration service instance."""
    global _orchestration_service
    _orchestration_service = service
    logger.info("Project orchestration service set for projects router")


def _get_orchestration_service() -> ProjectOrchestrationService:
    """Get the orchestration service instance."""
    if _orchestration_service is None:
        raise RuntimeError("Project orchestration service not initialized")
    return _orchestration_service


@projects_router.post(
    "",
    response_model=ProjectOut,
    status_code=status.HTTP_201_CREATED,
    summary="Create a new project",
    description="Create a new project with name, description, and optional tags.",
)
async def create_project(body: ProjectCreate):
    """
    Create a new project.
    
    This endpoint creates a new project in the database. The project ID
    is automatically generated by MongoDB.
    
    Required fields:
    - name: Project name (max 200 chars)
    - global_objective_type: Type of global objective
    - global_objective_target: Target magnitude of change
    
    Args:
        body: ProjectCreate schema with project data
        
    Returns:
        ProjectOut: Created project with ID and timestamps
        
    Raises:
        HTTPException: If validation fails (400) or creation fails (500)
    """
    try:
        # Validate required fields
        if not body.global_objective_type:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="global_objective_type is required",
            )
        if not body.global_objective_target:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="global_objective_target is required",
            )
        
        logger.info(f"Creating project: {body.name}")
        project = await services.create(body)
        return project
    except ValueError as e:
        # Validation errors from repository
        logger.warning(f"Validation error creating project: {e}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions
        raise
    except Exception as e:
        logger.error(f"Error creating project: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to create project: {str(e)}",
        )


@projects_router.get(
    "",
    response_model=List[ProjectOut],
    summary="List all projects",
    description="Get a list of all projects in the system.",
)
async def list_projects():
    """
    List all projects.
    
    Returns all projects from the database. For large datasets,
    consider adding pagination in the future.
    
    Returns:
        List[ProjectOut]: List of all projects
        
    Raises:
        HTTPException: If listing fails (500)
    """
    try:
        logger.info("Listing all projects")
        projects = await services.list_all()
        return projects
    except Exception as e:
        logger.error(f"Error listing projects: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to list projects: {str(e)}",
        )


@projects_router.get(
    "/{project_id}",
    response_model=ProjectOut,
    summary="Get a project by ID",
    description="Retrieve a specific project by its ID.",
)
async def get_project(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Get a project by ID.
    
    Args:
        project_id: MongoDB ObjectId as string
        
    Returns:
        ProjectOut: Project data
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Getting project: {project_id}")
        project = await services.get(project_id)
        
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        return project
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error getting project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get project: {str(e)}",
        )


@projects_router.patch(
    "/{project_id}",
    response_model=ProjectOut,
    summary="Update a project",
    description="Partially update a project. Only provided fields will be updated.",
)
async def update_project(
    patch: ProjectUpdate,
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Update a project.
    
    This endpoint supports partial updates (PATCH semantics). Only fields
    provided in the request body will be updated. The updated_at timestamp
    is automatically updated.
    
    Args:
        patch: ProjectUpdate schema with fields to update
        project_id: MongoDB ObjectId as string
        
    Returns:
        ProjectOut: Updated project data
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Updating project: {project_id}")
        project = await services.update(project_id, patch)
        
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        return project
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error updating project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update project: {str(e)}",
        )


@projects_router.delete(
    "/{project_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Delete a project",
    description="Delete a project from the system. This only deletes the project document, not associated data.",
)
async def delete_project(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Delete a project.
    
    This endpoint deletes the project document from the database.
    Note: This does NOT delete associated data (entities, relations, etc.).
    Use the clear_project_data endpoint if you need to clean up related data.
    
    Args:
        project_id: MongoDB ObjectId as string
        
    Returns:
        HTTP 204 No Content on success
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Deleting project: {project_id}")
        deleted = await services.delete(project_id)
        
        if not deleted:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        # Return 204 No Content (no response body)
        return None
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error deleting project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete project: {str(e)}",
        )


@projects_router.post(
    "/{project_id}/clear-data",
    summary="Clear project data",
    description="Delete all data associated with a project (entities, relations, etc.) but keep the project itself.",
)
async def clear_project_data(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Clear all data associated with a project.
    
    This endpoint deletes all related data (entities, relations, etc.)
    for a project, but keeps the project document itself. This is useful
    for resetting a project without deleting it.
    
    WARNING: This is a destructive operation. Use with caution.
    
    Args:
        project_id: MongoDB ObjectId as string
        
    Returns:
        Dictionary with deletion counts for each collection
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Clearing data for project: {project_id}")
        result = await services.clear_data(project_id)
        
        if "error" in result:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result["error"],
            )
        
        return result
    except ValueError as e:
        # Invalid ObjectId format
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        # Re-raise HTTP exceptions (like 404)
        raise
    except Exception as e:
        logger.error(f"Error clearing project data {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to clear project data: {str(e)}",
        )


@projects_router.patch(
    "/{project_id}/status",
    response_model=ProjectOut,
    summary="Update project status",
    description="Update the status of a project (draft, processing, validation, completed).",
)
async def update_project_status(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    status_value: ProjectStatus = Query(..., description="New project status"),
):
    """
    Update project status.
    
    Args:
        project_id: MongoDB ObjectId as string
        status_value: New project status (draft, processing, validation, completed)
        
    Returns:
        ProjectOut: Updated project data
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        logger.info(f"Updating project status: {project_id} -> {status_value}")
        
        # Create update patch with status
        patch = ProjectUpdate(status=status_value)
        project = await services.update(project_id, patch)
        
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        return project
    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error updating project status {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to update project status: {str(e)}",
        )


@projects_router.post(
    "/{project_id}/upload-files",
    summary="Upload files for a project",
    description="Upload base case documents and tabular data files for a project. Total file size limit is 25MB.",
)
async def upload_project_files(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
    base_case_files: Optional[List[UploadFile]] = File(None, description="Base case report documents (PDF)"),
    tabular_data_files: Optional[List[UploadFile]] = File(None, description="Tabular data files (PDF, Excel, CSV)"),
):
    """
    Upload files for a project.
    
    This endpoint accepts multiple files for base case documents and tabular data.
    Files are validated for type and total size (25MB limit across all files).
    
    Args:
        project_id: MongoDB ObjectId as string
        base_case_files: List of base case PDF files
        tabular_data_files: List of tabular data files (PDF, Excel, CSV)
        
    Returns:
        Dictionary with uploaded document IDs and processing status
        
    Raises:
        HTTPException: If validation fails (400) or project not found (404)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        # Validate file types and sizes
        MAX_TOTAL_SIZE = 25 * 1024 * 1024  # 25MB in bytes
        ALLOWED_BASE_CASE_TYPES = ["application/pdf"]
        ALLOWED_TABULAR_TYPES = [
            "application/pdf",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",  # Excel
            "application/vnd.ms-excel",  # Excel (old)
            "text/csv",
        ]
        
        total_size = 0
        document_ids = []
        
        # Process base case files
        base_case_doc_ids = []
        if base_case_files:
            for file in base_case_files:
                if file.content_type not in ALLOWED_BASE_CASE_TYPES:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid file type for base case: {file.content_type}. Only PDF is allowed.",
                    )
                
                file_bytes = await file.read()
                total_size += len(file_bytes)
                
                if total_size > MAX_TOTAL_SIZE:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Total file size exceeds 25MB limit",
                    )
                
                # Generate document ID (placeholder - actual storage will be implemented later)
                doc_id = str(uuid.uuid4())
                base_case_doc_ids.append(doc_id)
                document_ids.append(doc_id)
                logger.info(f"Uploaded base case file: {file.filename} -> {doc_id}")
        
        # Process tabular data files
        tabular_doc_ids = []
        if tabular_data_files:
            for file in tabular_data_files:
                if file.content_type not in ALLOWED_TABULAR_TYPES:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Invalid file type for tabular data: {file.content_type}. Allowed: PDF, Excel, CSV.",
                    )
                
                file_bytes = await file.read()
                total_size += len(file_bytes)
                
                if total_size > MAX_TOTAL_SIZE:
                    raise HTTPException(
                        status_code=status.HTTP_400_BAD_REQUEST,
                        detail=f"Total file size exceeds 25MB limit",
                    )
                
                # Generate document ID (placeholder - actual storage will be implemented later)
                doc_id = str(uuid.uuid4())
                tabular_doc_ids.append(doc_id)
                document_ids.append(doc_id)
                logger.info(f"Uploaded tabular data file: {file.filename} -> {doc_id}")
        
        # Validate at least one file of each type
        if not base_case_doc_ids:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one base case document is required",
            )
        if not tabular_doc_ids:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="At least one tabular data file is required",
            )
        
        # Update project with document IDs
        update_patch = ProjectUpdate(
            base_case_documents=base_case_doc_ids,
            tabular_data_documents=tabular_doc_ids,
        )
        updated_project = await services.update(project_id, update_patch)
        
        # Trigger document processing (placeholder)
        # In the future, this will call orchestration service
        orchestration = _get_orchestration_service()
        await orchestration.process_project_documents(
            project_id=project_id,
            global_objective_type=project.global_objective_type,
            global_objective_target=project.global_objective_target,
            base_case_document_ids=base_case_doc_ids,
            tabular_data_document_ids=tabular_doc_ids,
        )
        
        return {
            "project_id": project_id,
            "base_case_documents": base_case_doc_ids,
            "tabular_data_documents": tabular_doc_ids,
            "total_files": len(document_ids),
            "total_size_bytes": total_size,
            "message": "Files uploaded successfully. Processing started.",
        }
        
    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except RuntimeError as e:
        logger.error(f"Orchestration service not initialized: {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Document processing service not available",
        )
    except Exception as e:
        logger.error(f"Error uploading files for project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to upload files: {str(e)}",
        )


@projects_router.get(
    "/{project_id}/report",
    summary="Get project report",
    description="Generate and retrieve markdown report for a project.",
)
async def get_project_report(
    project_id: str = Path(..., description="Project ID (MongoDB ObjectId as string)"),
):
    """
    Get project report in markdown format.
    
    This endpoint generates a comprehensive markdown report including
    project details, extracted entities, cost estimates, and recommendations.
    
    Args:
        project_id: MongoDB ObjectId as string
        
    Returns:
        Dictionary with markdown report content
        
    Raises:
        HTTPException: If project not found (404) or invalid ID format (400)
    """
    try:
        # Validate project exists
        project = await services.get(project_id)
        if not project:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Project not found: {project_id}",
            )
        
        # Generate report using orchestration service
        orchestration = _get_orchestration_service()
        markdown_content = await orchestration.generate_report(project_id)
        
        return {
            "project_id": project_id,
            "report": markdown_content,
            "format": "markdown",
        }
        
    except ValueError as e:
        logger.warning(f"Invalid project_id format: {project_id}")
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e),
        )
    except HTTPException:
        raise
    except RuntimeError as e:
        logger.error(f"Orchestration service not initialized: {e}")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Report generation service not available",
        )
    except Exception as e:
        logger.error(f"Error generating report for project {project_id}: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate report: {str(e)}",
        )


# WebSocket Support (Future Enhancement)
# ======================================
# 
# If real-time updates are needed for projects, WebSocket support can be added here.
# Example:
#
# @projects_router.websocket("/{project_id}/ws")
# async def project_websocket(websocket: WebSocket, project_id: str):
#     """
#     WebSocket endpoint for real-time project updates.
#     
#     Clients can connect to receive real-time notifications when:
#     - Project data is updated
#     - Project data is added/deleted
#     """
#     await websocket.accept()
#     try:
#         # Subscribe to project change events
#         # Send updates as they occur
#         while True:
#             # Wait for events and send to client
#             await websocket.send_json({"type": "update", "data": {...}})
#     except WebSocketDisconnect:
#         # Client disconnected
#         pass
#
# This would require:
# 1. A pub/sub system (like the progress publisher used in files.py)
# 2. Event emission in repository methods
# 3. WebSocket connection management
#
# For now, standard REST endpoints are sufficient for CRUD operations.

